//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAccount.ServiceAccount {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Accounts", Namespace="http://schemas.datacontract.org/2004/07/NEITStoreOrdersService")]
    [System.SerializableAttribute()]
    public partial class Accounts : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountType {
            get {
                return this.AccountTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountTypeField, value) != true)) {
                    this.AccountTypeField = value;
                    this.RaisePropertyChanged("AccountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Options {
            get {
                return this.OptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.OptionsField, value) != true)) {
                    this.OptionsField = value;
                    this.RaisePropertyChanged("Options");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerName {
            get {
                return this.OwnerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerNameField, value) != true)) {
                    this.OwnerNameField = value;
                    this.RaisePropertyChanged("OwnerName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAccount.INEITStoresOrderService")]
    public interface INEITStoresOrderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INEITStoresOrderService/ReturnAmountEarned", ReplyAction="http://tempuri.org/INEITStoresOrderService/ReturnAmountEarnedResponse")]
        float ReturnAmountEarned(float balance, float interest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INEITStoresOrderService/ReturnAmountEarned", ReplyAction="http://tempuri.org/INEITStoresOrderService/ReturnAmountEarnedResponse")]
        System.Threading.Tasks.Task<float> ReturnAmountEarnedAsync(float balance, float interest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INEITStoresOrderService/GetBankInformation", ReplyAction="http://tempuri.org/INEITStoresOrderService/GetBankInformationResponse")]
        TestAccount.ServiceAccount.Accounts GetBankInformation(string AccountID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INEITStoresOrderService/GetBankInformation", ReplyAction="http://tempuri.org/INEITStoresOrderService/GetBankInformationResponse")]
        System.Threading.Tasks.Task<TestAccount.ServiceAccount.Accounts> GetBankInformationAsync(string AccountID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INEITStoresOrderServiceChannel : TestAccount.ServiceAccount.INEITStoresOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NEITStoresOrderServiceClient : System.ServiceModel.ClientBase<TestAccount.ServiceAccount.INEITStoresOrderService>, TestAccount.ServiceAccount.INEITStoresOrderService {
        
        public NEITStoresOrderServiceClient() {
        }
        
        public NEITStoresOrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NEITStoresOrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NEITStoresOrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NEITStoresOrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public float ReturnAmountEarned(float balance, float interest) {
            return base.Channel.ReturnAmountEarned(balance, interest);
        }
        
        public System.Threading.Tasks.Task<float> ReturnAmountEarnedAsync(float balance, float interest) {
            return base.Channel.ReturnAmountEarnedAsync(balance, interest);
        }
        
        public TestAccount.ServiceAccount.Accounts GetBankInformation(string AccountID) {
            return base.Channel.GetBankInformation(AccountID);
        }
        
        public System.Threading.Tasks.Task<TestAccount.ServiceAccount.Accounts> GetBankInformationAsync(string AccountID) {
            return base.Channel.GetBankInformationAsync(AccountID);
        }
    }
}
